name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Change directory to portfolio
        run: cd portfolio

      - name: Install dependencies
        run: npm install
        working-directory: portfolio

      - name: Build the React app
        run: npm run build
        working-directory: portfolio

      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v3
        with:
          path: portfolio/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
